// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8hzAB77brI25y9Z_wbJVG5CmnnKFKY1k',
    appId: '1:308614603316:web:013928a5276ef6ea75e061',
    messagingSenderId: '308614603316',
    projectId: 'app-h5p-2c7df',
    authDomain: 'app-h5p-2c7df.firebaseapp.com',
    storageBucket: 'app-h5p-2c7df.firebasestorage.app',
    measurementId: 'G-KCEG3XKWZQ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8hzAB77brI25y9Z_wbJVG5CmnnKFKY1k',
    appId: '1:308614603316:web:e18175da7d4c26f075e061',
    messagingSenderId: '308614603316',
    projectId: 'app-h5p-2c7df',
    authDomain: 'app-h5p-2c7df.firebaseapp.com',
    storageBucket: 'app-h5p-2c7df.firebasestorage.app',
    measurementId: 'G-T4QT77X9P4',
  );
}
